### ISSUE TITLE
Cannot run main.py in /datagen/img_generation

### ISSUE THREAD

**Issue by Mohamed-Omran** [microsoft/AirSim-Drone-Racing-VAE-Imitation#8]
when running the `main.py` file I het this error
```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    pose_sampler = PoseSampler(num_samples, dataset_path)
  File "/home/momo/Desktop/GP/datagen/img_generator/PoseSampler.py", line 55, in __init__
    self.configureEnvironment()
  File "/home/momo/Desktop/GP/datagen/img_generator/PoseSampler.py", line 88, in configureEnvironment
    self.tgt_name = self.client.simSpawnObject("gate", "RedGate16x16", Pose(position_val=Vector3r(0,0,15)), 1.5)
  File "/home/momo/miniconda3/envs/GP/lib/python3.7/site-packages/airsim/client.py", line 471, in simSpawnObject
    return self.client.call('simSpawnObject', object_name, asset_name, pose, scale, physics_enabled)
  File "/home/momo/miniconda3/envs/GP/lib/python3.7/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/momo/miniconda3/envs/GP/lib/python3.7/site-packages/msgpackrpc/future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: function 'simSpawnObject' (called with 5 arg(s)) threw an exception. The exception is not derived from std::exception. No further information available.
```
I am using: 

airsim-1.6.0
msgpack-python-0.5.6
msgpack-rpc-python-0.4.1
numpy-1.21.5
opencv-contrib-python-4.5.5.64
tornado-4.5.3

on KDE neon
The airsim binaries on google drive run fine.

**Comment by Mohamed-Omran** [comment]
I found out that I had an older version of the code.
The master branch version worked.
